### ISSUE TITLE
unsupported URL protocol when used with private registry

### ISSUE THREAD

**Issue by scullionw** [pksunkara/cargo-workspaces#102]
- I am using a shipyard.rs private registry
- I can publish using `cargo release` (so the url works)

When i try publishing with this crate I get:

```
Updating crates.io index
info version committing changes
info version tagging
error: crates index error: unsupported URL protocol; class=Net (12)
```

is this expected?

**Comment by pksunkara** [comment]
I need more information. What's the URL for the registry?

**Comment by scullionw** [comment]
```
[registries.myregistry]
index = "ssh://git@ssh.shipyard.rs/myregistry/crate-index.git"
```

**Comment by pksunkara** [comment]
Looks like it's an issue with Index crawler. https://github.com/frewsxcv/rust-crates-index/issues/37.

We will be removing it as part of #93 though soon.

**Comment by j-baker** [comment]
It's worth noting that this also cannot handle `sparse+https` if there is no corresponding git index. rust-crates-index assumes that any sparse registry has a corresponding un-sparse registry per https://github.com/frewsxcv/rust-crates-index/issues/128 and explodes violently if this is not true! A solution to #93 would be much appreciated.

**Comment by pksunkara** [comment]
I have switched out the dependency for reading the index to https://github.com/EmbarkStudios/tame-index and this should now be fixed in master. Can you guys please try it out before I release?
