### ISSUE TITLE
Support fixed version crates

### ISSUE THREAD

**Issue by qvignaud** [pksunkara/cargo-workspaces#104]
Hi all,

In one of our workspaces, we have a crate that have fixed version that should never be updated at this point.

The `package.metadata.workspaces.independent` property is halfway what we would like, but it still proposes version upgrade when running `cargo ws <bump>`, while it should just not be considered at all.

A `package.metadata.workspaces.fixed` property or similar (`ignore`, `avoid`, etc.) should be added.

I may take a look and implement it by my own MR, just let me know if something similar is already planned or not.

**Comment by pksunkara** [comment]
You should be able to use `--ignore-changes` flag in the `cargo ws version` command to ignore that crate.

> we have a crate that have fixed version that should never be updated at this point. 

Can I know the reason why?

**Comment by pksunkara** [comment]
@qvignaud Please let me know if my comment does not resolve your issue and I will re-open the issue.

**Comment by qvignaud** [comment]
Actually it worked fine for our latest releases, the concerned crate didn't had its version updated.
Not really sure what changed, as it didn't seems we made any update of `ws`, so it should have been a problem on our side !

> > we have a crate that have fixed version that should never be updated at this point.
> 
> Can I know the reason why?

We have two different uses cases:
- in one workspace, one of the member is a component that is step-by-step extracted from the other crates and is functionally distinct, it will become a totally separated crate/project/repo at the end by still require some work to do so;
- in another workspace, we're developing an app composed of many crates that live altogether, but the bundling/front crates that are the technical Android/iOS/Mac/Windows app releases follows their own and independent versioning.

Hope it helps you, and anyway great job!

**Comment by pksunkara** [comment]
>Actually it worked fine for our latest releases, the concerned crate didn't had its version updated.

That's because you probably have no code changes in that crate. If you did, it would have still asked you. You can either choose the `skip`, or run the command with `--ignore-changes` in  the first place.
