### ISSUE TITLE
Need to update references to the updated package

### ISSUE THREAD

**Issue by rgiot** [pksunkara/cargo-workspaces#106]
Hello, I've just applied the following command  ` cargo ws version`  to my repository.
it generated the following patch: https://github.com/cpcsdk/rust.cpclib/commit/06894a63b7b6fcb1815786caef4c460777c41046
which has not modified the following file: https://github.com/cpcsdk/rust.cpclib/blob/b0c9e00acaac753a4854a08112bdc69e2c772dc7/Cargo.toml

I would have expect some lines like

` ` ` 
cpclib = {version="0.7.0",path="cpclib", default-features=false}
cpclib-asm = {version= "0.7.1",path="cpclib-asm", default-features=false}
` ` ` 

to be modified as
` ` ` 
cpclib = {version="0.7.1",path="cpclib", default-features=false}
cpclib-asm = {version= "0.7.2",path="cpclib-asm", default-features=false}
` ` ` 

Am i wrong ? or does my workspace organization is too specific for the toom ?

**Comment by pksunkara** [comment]
Patches don't need to be updated. Use `--exact` if needed.
