### ISSUE TITLE
cargo ws publish doesnt work

### ISSUE THREAD

**Issue by XAMPPRocky** [pksunkara/cargo-workspaces#12]
Every time I run `cargo ws publish` it fails with the following. 

```
info version committing changes
info version tagging
info git pushing
error: unable to push to remote, out = , err = Everything up-to-date
```

**Comment by pksunkara** [comment]
It pushes to the git origin remote if you don't have `--no-git-push` enabled. If you don't want to version and just publish from already existing commits, you would need to give `cargo ws publish from-git`

**Comment by pksunkara** [comment]
Or if you are versioning it, when the tool commits, is there a git hook that is doing auto pushing before the tool can push? In that case, using `--no-git-push` should help.

**Comment by pksunkara** [comment]
It's just that a lot of people have a lot of different ways on how to do things, so I made the tool more configurable.

**Comment by pksunkara** [comment]
I am sorry I don't understand what you are saying. Can you explain a bit more? What's the full command you ran here and what did you want to happen?

**Comment by XAMPPRocky** [comment]
I just ran `cargo ws publish patch` on a regular git repository with no kinds of hooks or anything. https://github.com/fluent-templates to be exact.

**Comment by pksunkara** [comment]
That should not fail.

* It commits the version changes
* Tags the commit
* Pushes the commit and tags

It looks like the push is failing is because something else already pushed the commit. 

I will actually fix for this scenario. But I am curious what pushed the commit if you said you don't have any hooks.

**Comment by XAMPPRocky** [comment]
The something else is `cargo-ws` is pushing at an earlier point. I can replicate this behaviour.

**Comment by pksunkara** [comment]
I wasn't able to replicate this behaviour. I used this just yesterday too. What version are you using? And what platform? Can you also tell me your git version?

**Comment by XAMPPRocky** [comment]
I'm on macOS Catalina.
```
git version 2.26.2
cargo-workspaces 0.2.4
```

**Comment by pksunkara** [comment]
There's nothing about any behaviour change from `git` release notes. Can you please give me some small info before I start extensive debugging? Please run `cargo ws publish --no-git-push patch` and check the `origin` remote. Were the newly created commits pushed or not?

**Comment by XAMPPRocky** [comment]
`cargo ws publish --no-git-push patch` This worked.

**Comment by pksunkara** [comment]
But your remote still has the new commits?

**Comment by XAMPPRocky** [comment]
No, it worked as expected. This only happens with `cargo ws publish patch`.

**Comment by pksunkara** [comment]
What is your `git config --global push.followTags` and `git config push.followTags`?

**Comment by XAMPPRocky** [comment]
My `followTags` config is `true`.

**Comment by pksunkara** [comment]
Yup that's the issue here. I know a better way to fix this now. Thanks
