### ISSUE TITLE
Cannot exit creation of crate using `CTRL`+`C` 

### ISSUE THREAD

**Issue by FireFragment** [pksunkara/cargo-workspaces#143]
During the first step of creating a new crate in the workspace with `cargo workspaces create` (naming the crate), pressing `CTRL`+`C` does not interrupt the command as expected. 

### Steps to reproduce

1. Create a new workspace with:
   ```
   cargo workspaces init
   ```
2. Run:
   ```
   cargo workspaces create test
   ```
3. You will be prompted to enter crate name. Now press `CTRL`+`C`

### Expected behavior

The program should stop

### Actual behavior

The prompt does not dieappear and `^C` is written to the prompt

**Comment by pksunkara** [comment]
Is this with the latest version? I see the code handling for ctrl-c properly.

**Comment by FireFragment** [comment]
I'm using 0.3.0
PS. I added a video to the original post
