### ISSUE TITLE
cannot publish with sparse registries

### ISSUE THREAD

**Issue by j-baker** [pksunkara/cargo-workspaces#146]
When I try to publish with sparse registries, I get:

```
error: crates index error: Protocol Ext("sparse+https") of url "sparse+https://$MY_REGISTRY" is denied per configuration
```

If I github code search for this, I find this error has come from gitoxide, https://github.com/search?q=%22is+denied+per+configuration%22&type=code, which is the library Cargo uses to talk to git repositories.

This makes me believe that cargo-workspace-publish is trying to publish using a non-sparse URL.

Looking at https://github.com/pksunkara/cargo-workspaces/blob/master/cargo-workspaces/src/publish.rs#L112, it looks like `registry+` is prepended to every url, meaning that with my sparse registry, the url being passed to the is_published check happening in the publish is `registry+sparse+https://$MY_REGISTRY` which is invalid and so passed through as a git check.

I think that blanket prepending registry+ is an incorrect algorithm. My suspicion is that this check should be skipped as for larger registries it would tend to take an unnecessarily large amount of time.

**Comment by pksunkara** [comment]
I am using `tame_index` which I am not familiar with. @Jake-Shadle would you be able to help me understand what I am doing wrong here?

This is also possibly related to #79

**Comment by Jake-Shadle** [comment]
The issue is correct, prepending `registry+` to the URL will cause the URL to be misidentified as a [git registry url](https://github.com/EmbarkStudios/tame-index/blob/f6f809b571e4ddfdd0e9a9aee31b358bf9c67e2f/src/utils.rs#L120-L139).

**Comment by pksunkara** [comment]
@j-baker I have committed the fix to master. Can you please check and confirm so that I can make a release?

**Comment by j-baker** [comment]
I can confirm that this fixes one part of my issue, and that https://github.com/pksunkara/cargo-workspaces/pull/148 fixes the other parts.

**Comment by j-baker** [comment]
@pksunkara any chance you could release?

**Comment by pksunkara** [comment]
I was waiting for your input on https://github.com/pksunkara/cargo-workspaces/pull/148#issuecomment-1875207574. Will do so now.
