### ISSUE TITLE
Extremely slow to change versions

### ISSUE THREAD

**Issue by j-baker** [pksunkara/cargo-workspaces#147]
I have a workspace with about 30 crates. They have a few registries

I run

```
cargo workspaces version --no-git-commit -y --exact --force '*' -a custom "1.2.0"
```

to basically try to update all the versions. My hope is that this returns very quickly. Unfortunately it takes 8m14s. This is because for each crate in the workspace, this project runs `cargo update -p $crateName`. I assume that this is done in order to ensure that Cargo.lock is up to date.

I'm wondering if this should instead run `cargo update -w` at the end, once.

**Comment by pksunkara** [comment]
Feel free to check with master now.
