### ISSUE TITLE
Bumping workspace crates misses 1 crate causing a dependency failure

### ISSUE THREAD

**Issue by amaanq** [pksunkara/cargo-workspaces#151]
You can try this yourself in the [tree-sitter](https://github.com/tree-sitter/tree-sitter) repository:

`cargo workspaces version minor --no-git-commit --yes`

```
info looking for changes since v0.22.5
info current common version 0.22.5

Changes:
 - tree-sitter-cli: 0.22.5 => 0.23.0
 - tree-sitter-highlight: 0.22.5 => 0.23.0
 - tree-sitter: 0.22.5 => 0.23.0
 - tree-sitter-loader: 0.22.5 => 0.23.0
 - tree-sitter-tags: 0.22.5 => 0.23.0

error: failed to select a version for the requirement `tree-sitter-config = "^0.22.2"`
candidate versions found which didn't match: 0.23.0
location searched: /Users/amaanq/tree-sitter/cli/config
required by package `tree-sitter-cli v0.23.0 (/Users/amaanq/tree-sitter/cli)`
info success ok
```

I don't remember this failing before, not sure how recent it is. It'd be nice if tree-sitter-config got bumped as well, since every other crate does get bumped correctly. Thanks!

**Comment by pksunkara** [comment]
That's because `tree-sitter-config` doesn't have any changes. Can you try adding `--force *` to the command? That would force all crates to be bumped even if they have no changes.
