### ISSUE TITLE
Add option to `exec` to limit execution to crates that will publish

### ISSUE THREAD

**Issue by leighmcculloch** [pksunkara/cargo-workspaces#156]
Similar to `list` it would be helpful if the `exec` subcommand had an option to only execute with the crates that the `publish` command will publish, i.e. that don't have `publish = false` in their toml file.

It would make it possible for scripts to use just the crates that the publish command will publish when called.

**Comment by pksunkara** [comment]
Isn't that the default behaviour? By default, only publishable crates are shown. Private crates are shown only if `--all` is given. https://github.com/pksunkara/cargo-workspaces#list

**Comment by leighmcculloch** [comment]
Oops, I stated `list` above, but I meant to write `exec`. 🤦🏻 I'll edit the description and title to correct it.
