### ISSUE TITLE
Cargo workspaces v0.2.12 no longer compiles

### ISSUE THREAD

**Issue by nathanwhit** [pksunkara/cargo-workspaces#16]
Failure first seen [here](https://github.com/rust-lang/chalk/runs/1139093851). I can reproduce this locally as well. The failure is caused by a bunch of instances of the following error:
<img width="808" alt="Screen Shot 2020-09-20 at 2 36 03 PM" src="https://user-images.githubusercontent.com/17734409/93719131-9ee43c00-fb4e-11ea-966e-5a1976519c72.png">

**Comment by pksunkara** [comment]
It's because clap beta2 release. I will fix it now.

**Comment by pksunkara** [comment]
Released v0.2.13
