### ISSUE TITLE
Dev-dependencies that contain a `cfg` don't get wiped on publish leading to failures

### ISSUE THREAD

**Issue by jkelleyrtp** [pksunkara/cargo-workspaces#164]
If you have a dev-dependency block that is cfged (say, per target), it doesn't get wiped when publish occurs, leading to publish failures.

Like this block
```toml
[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
getrandom = { version = "0.2.12", features = ["js"] }
tokio = { version = "1.16.1", default-features = false, features = [
    "sync",
    "macros",
    "io-util",
    "rt",
    "time"
] }
```

**Comment by jkelleyrtp** [comment]
We just tested it with our 0.6.0-alpha.0 release and while it removed the header itself it did not remove the dependencies under that header: the bug still remains but under different behavior

**Comment by pksunkara** [comment]
> it did not remove the dependencies under that header

Can you please provide me more information?

* cargo-ws version
* Resultant block? (I didn't understand what you meant by not removing the dependencies under the header)
