### ISSUE TITLE
`cargo ws plan` prints an error that probably should be an `info`

### ISSUE THREAD

**Issue by martin-g** [pksunkara/cargo-workspaces#167]
Hi,

I am using v0.3.5

```
$ cargo ws plan
error: config value `http.cainfo` is not set
apache-avro-test-helper
apache-avro-derive
apache-avro
``` 

The error looks like it should be an `info` or at most a `warning` to me.
https://doc.rust-lang.org/cargo/reference/config.html#httpcainfo is an optional setting, so IMO it should not lead to errors.

**Comment by pksunkara** [comment]
It's coming from cargo. Unfortunately, we can't do anything.
