### ISSUE TITLE
Order of `cargo workspaces exec`

### ISSUE THREAD

**Issue by cutsoy** [pksunkara/cargo-workspaces#17]
Maybe this is already the case, but it would be quite helpful if the `exec` command also guarantees a correct order according to the intra-workspace dependencies (just like `publish` does).

Based on the current code, I suspect the order is currently inherited from the order of `cargo_metadata::Metadata::packages` ([this one](https://docs.rs/cargo_metadata/0.11.3/cargo_metadata/struct.Metadata.html#structfield.packages)). They don't guarantee any particular order. So I think WS has to implement this behavior itself.

I briefly looked at your implementation for the `publish` command, but I can't identity the portion of code that is responsible for determining a correct order. Otherwise, I don't think it necessarily has to be very difficult to port that same semantic to the `exec` command.

Any thoughts?

**Comment by pksunkara** [comment]
[Here](https://github.com/pksunkara/cargo-workspaces/blob/master/cargo-workspaces/src/publish.rs#L117) is the code that sorts the dependencies in order. I am open to PRs, so you can refactor that out a bit and use it in exec too.

**Comment by cutsoy** [comment]
Ah, I overlooked the fact that it is using `indexmap`. Nice! I will try to refactor that bit later today (hopefully) and submit a PR. Thanks!

**Comment by pksunkara** [comment]
@cutsoy Any update on this?
