### ISSUE TITLE
specifying git and registry is not allowed when it should

### ISSUE THREAD

**Issue by danielementary** [pksunkara/cargo-workspaces#172]
when running either `cargo workspaces version` or `cargo workspaces publish`, I get the following:

```
thread 'main' panicked at /.../cargo/registry/src/index.crates.io-6f17d22bba15001f/cargo-workspaces-0.3.6/src/main.rs:78:35:
called `Result::unwrap()` on an `Err` value: CargoMetadata { stderr: "error: failed to load manifest for workspace member `/.../cli`
referenced by workspace at `/.../Cargo.toml`

Caused by:
  failed to parse manifest at `/.../cli/Cargo.toml`

Caused by:
  dependency (...) specification is ambiguous. Only one of `git` or `registry` is allowed.\n" }
```

However providing `registry` along with `git` should be allowed: https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#multiple-locations

**Comment by pksunkara** [comment]
That section talks about having `git` and `path` or `registry` and `path`. You cannot have both `git` and  `registry`.

**Comment by danielementary** [comment]
According to the link I shared, you should be able to have `registry` in addition to `path` or `git`.

**Comment by pksunkara** [comment]
> It is possible to specify both a registry version and a git or path location. 

That is taking about `version`. Maybe I am misunderstanding that section but can you please expand more on why you think `registry` and `git` should work?

**Comment by danielementary** [comment]
From the link:
> It is possible to specify both a registry version and a git or path location.

As far as I understand you should be able to provide a registry/version + a git/path location. I am no longer running into this issue, maybe there was another misconfigured cargo setting. Thanks for you help
