### ISSUE TITLE
display published version for list command

### ISSUE THREAD

**Issue by sehz** [pksunkara/cargo-workspaces#18]
This is great utility.

It would be handy if `list` command display last published version of crates as well.  So something like this:
```
$ cargo ws list -l
crates        current_version         published_version
-------      ----------------        -----------------
echo          0.2.0                          0.1.2
```

**Comment by pksunkara** [comment]
Unfortunately, I am considering this as out of scope for this tool. There are other tools out there that gets you the info of current published versions.
