### ISSUE TITLE
"api error" on 200 OK

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [pksunkara/cargo-workspaces#25]
I love the idea of this tool (looking for similar for a while due to a complex workspace project with many crates I have), although having some initial usage problems.

On first attempt to publish (after versioning successfully) using `cargo ws publish --from-git` I get this error:

```
error: api errors (status 200 OK): crate version `0.12.0` is already uploaded
```

- The version 0.12.0 is NOT in crates.io so not sure why it says "uploaded"
- 200 OK should be success and not detected/reported as an API error, no?

**Comment by pksunkara** [comment]
What's the crate?

**Comment by pksunkara** [comment]
If you check [here](https://github.com/pksunkara/cargo-workspaces/blob/34d43f15ce2b81ed69d162523a6b2316de53e5e7/cargo-workspaces/src/publish.rs#L90-L92), cargo is returning an error (even with 200 OK from crates.io).

Also, crates.io is a tiny bit slow to show an uploaded version. You might have uploaded it in one of your previous initial runs.

Try the `--skip-published`
