### ISSUE TITLE
More info on how to start using the tool

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [pksunkara/cargo-workspaces#27]
Sorry for all the issues, but I still can't get it to publish correctly:

I am trying to publish a new version of the crates in this workspace project:
https://github.com/andrewdavidmackenzie/flow

- All the versions are already at: `version = "0.21.0`
- all inter-dependencies have the structure: `flow_impl = {path = "../flow_impl", version = "0.21.0" }` 
- workspace Cargo.toml has 8 members: `members = ["flowc", "flowr", "flowrstructs", "provider", "flow_impl", "flow_impl_derive", "flowstdlib", "flowide"]`

When I try to publish (selecting a version bump to 0.22.0):
- Only seems to "detect change" in some crates (missing: "flow_impl", "flow_impl_derive", "provider")
- It seems to think "0.21.0" of "flow_impl" (the lowest node in the dependency tree) should be already published, and can't find it and fails.

Not sure what I'm doing wrong....

```
andrew@MacBook-Pro-4 flow % cargo ws publish 
info looking for changes since flow_impl@0.21.0
info current common version 0.21.0
✔ Select a new version (currently 0.21.0) · Minor (0.22.0)

Changes:
 - flowc: 0.21.0 => 0.22.0
 - flowide: 0.21.0 => 0.22.0
 - flowr: 0.21.0 => 0.22.0
 - flowrstructs: 0.21.0 => 0.22.0
 - flowstdlib: 0.21.0 => 0.22.0

✔ Are you sure you want to create these versions? · yes
    Updating crates.io index
    Updating flowc v0.21.0 (/Users/andrew/workspace/flow/flowc) -> v0.22.0
    Updating flowide v0.21.0 (/Users/andrew/workspace/flow/flowide) -> v0.22.0
    Updating flowr v0.21.0 (/Users/andrew/workspace/flow/flowr) -> v0.22.0
    Updating flowrstructs v0.21.0 (/Users/andrew/workspace/flow/flowrstructs) -> v0.22.0
    Updating flowstdlib v0.21.0 (/Users/andrew/workspace/flow/flowstdlib) -> v0.22.0
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
    Updating crates.io index
info version committing changes
info version tagging
info git pushing
    Updating crates.io index
   Packaging flowrstructs v0.22.0 (/Users/andrew/workspace/flow/flowrstructs)
   Verifying flowrstructs v0.22.0 (/Users/andrew/workspace/flow/flowrstructs)
error: failed to verify package tarball

Caused by:
  failed to select a version for the requirement `flow_impl = "^0.21.0"`
  candidate versions found which didn't match: 0.14.0, 0.12.0, 0.11.0, ...
  location searched: crates.io index
  required by package `flowrstructs v0.22.0 (/Users/andrew/workspace/flow/target/package/flowrstructs-0.22.0)`
error: unable to publish package flowrstructs
```

**Comment by pksunkara** [comment]
It recognizes only the changed crates using https://github.com/pksunkara/cargo-workspaces#changed. And it would work properly if not for the fact that you did https://github.com/andrewdavidmackenzie/flow/commit/47a473135db9ca4dfe8d16ea50122b572bf7eb10#diff-7943bc5e94d320e894f58080d110d10bc58a430ff60467de5ed502c2e6fcc2f4R28 where you manually put `flow_impl` at 0.21.0.

Do not manually change your Cargo.toml. Point the versions in `Cargo.toml` to the existing versions which are published. (Assume you individually published all 0.21.0 now and all the versions in `Cargo.toml` point to 0.21.0).

Now, change some code in `flowc`, and try to run the publish.

NOTE: If you don't use `--exact`, it will intelligently publish only some of the crates since the default is `^0.x.y`.

**Comment by andrewdavidmackenzie** [comment]
OK, I'm manually publishing the versions expected to be published - and then will try again on my next code change. Thanks for the help.

**Comment by pksunkara** [comment]
You can also do the current manual publishing by using `--from-git` and `--skip-published`

**Comment by pksunkara** [comment]
@andrewdavidmackenzie Hey, do you think it would be easier if I had a gif of a sample execution of publish?

**Comment by andrewdavidmackenzie** [comment]
In general, that would be cool, but I don't think it would have helped me in this particular case.

I think it's a combination of how it works in general, and in particular to the current version number in the Cargo.toml, changes made, and what (if any) was the last version published, and the need to NOT manually edit that  number once you start using cargo-workspace.

**Comment by pksunkara** [comment]
Yeah, I was thinking that I will also add a sentence or two in that gif regarding those starting conditions.

How are you feeling about using the tool now once you got it working?

**Comment by andrewdavidmackenzie** [comment]
I just did a publish of that large workspace project and everything seemed to go very smoothly.

It feels a little like magic, as I am not 100% clear on what it's doing the whole time - but it worked well!

**Comment by pksunkara** [comment]
I did explain it [here](https://github.com/pksunkara/cargo-workspaces#version), but this tool mostly follows what [lerna](https://lerna.js.org) does which is very successful and well known.
