### ISSUE TITLE
Per-crate version tag prefixes

### ISSUE THREAD

**Issue by mathstuf** [pksunkara/cargo-workspaces#3]
In some my multi-crate repositories, tagging needs to be distinct per crate. For example, the main repo is `git-checks` because it used to be a single crate. It is now three: `git-check-core` and `git-checks-config` are new.

Tagging is:

  - `vX.Y.Z` for `git-checks`
  - `git-checks-core/vX.Y.Z` for `git-checks-core`
  - `git-checks-config/vX.Y.Z` for `git-checks-config`

Supporting per-crate prefixes would be great.

**Comment by mathstuf** [comment]
Thanks!

**Comment by pksunkara** [comment]
@mathstuf No problem. Please do give me some feedback on how it went when you use the tool. Would appreciate it.

**Comment by mathstuf** [comment]
Will do. Not sure when my next release stack will be, but should be before the end of the month.
