### ISSUE TITLE
Feature request: option for force incrementing versions even when there's no change

### ISSUE THREAD

**Issue by yutannihilation** [pksunkara/cargo-workspaces#34]
Thanks for this great tool. I'm now considering to use `cargo ws version` on [a project that I'm involved in](https://github.com/extendr/extendr). The project has several crates, and since these are tightly related with each other, we want to publish all of them with the same version at the same time, even when there's no actual changes. If I understand correctly, `cargo ws version` skips the crates with no changes. Could you consider adding an option to force incrementing versions?

**Comment by pksunkara** [comment]
`--force '*'`. Please read all the options available.

**Comment by yutannihilation** [comment]
Aw, sorry. I noticed the option, but didn't understand the meaning... Thanks for your help!
