### ISSUE TITLE
Publishing hangs on upload

### ISSUE THREAD

**Issue by olanod** [pksunkara/cargo-workspaces#37]
When I run the `cargo workspaces publish` the command hangs uploading the package, I then kill it with Ctr+C but the upload actually works. For reference, `cargo publish` alone works as expected.

**Comment by pksunkara** [comment]
Ooh. I have been trying to catch this bug for quite a few days. I have been unable to reproduce this. This had initially happened on https://github.com/rust-lang/chalk.

I added support for `--verbose` option to give me more information. Next time you publish, can you please use it?

**Comment by olanod** [comment]
Didn't see much, after the very verbose compilation process it stuck with this
```
    Finished dev [unoptimized + debuginfo] target(s) in 19.64s
   Uploading my_package v0.x.x.-alpha.0 (/the/path)
debug cargo stdout
info waiting ...
```
Does it tell you anything?
