### ISSUE TITLE
extra `=` added when do version custom command

### ISSUE THREAD

**Issue by gengjiawen** [pksunkara/cargo-workspaces#38]
I am executing `cargo workspaces version custom --exact 0.5.0 --no-git-commit`

The generated patch with extra `=`
![image](https://user-images.githubusercontent.com/3759816/105699853-f6eadf00-5f42-11eb-9096-dc0e5883e843.png)

**Comment by pksunkara** [comment]
Yeah because you are passing `exact`

**Comment by gengjiawen** [comment]
> Yeah because you are passing `exact`

I thought `=` is invalid in rust version number. Thanks for explanation.
