### ISSUE TITLE
[BUG] Cargo workspaces version does not change dev-dependencies

### ISSUE THREAD

**Issue by edwin0cheng** [pksunkara/cargo-workspaces#39]
Repro :

https://github.com/edwin0cheng/bug-no-dev

After running :

```bash
cargo workspaces version --no-git-commit custom 0.0.40
```

The content of `crates/bar/Cargo.toml` :

```
[package]
name = "bar"
version = "0.0.40"
authors = ["edwin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
foo = {path = "../foo", version="0.0.0"}
```

Note that the `foo` version number didn't change.

**Comment by pksunkara** [comment]
@edwin0cheng That's because dev deps are not recommended to have `version` at all if they use `path`. So, the tool doesn't actually touch them at all in the first place.

**Comment by edwin0cheng** [comment]
Sound reasonable ! 

Thanks for the help.

**Comment by leighmcculloch** [comment]
I ran into this same issue for a crate that is intended to publish its tests, which is an optional thing crates can do. For crates that want to do this dev_dependencies needs to contain versions, and `cargo-workspaces` doesn't update the versions of dev dependencies which means after running a version change with it, the Cargo.toml's are left with multiple versions being referenced.

I think `cargo-workspace version` should still update the dev_dependencies `version` fields  if they are present. If people are using `path` fields instead and no `version` field it can simply ignore it.
