### ISSUE TITLE
Exclude crates

### ISSUE THREAD

**Issue by Yuri6037** [pksunkara/cargo-workspaces#45]
In my project workspace, I have 3 cargo crates. 2 of them are to be published if their version changes. However the third one is only used some kind of integration testing program: it should not be published to crates.io.

Is there any such option to exclude a specific crate from publication? If not, I'd like to request this feature.

**Comment by pksunkara** [comment]
Try `publish = false`

**Comment by Yuri6037** [comment]
Thank you I didn't know about the existance of that feature.
