### ISSUE TITLE
Update workspace.members when create

### ISSUE THREAD

**Issue by dcompoze** [pksunkara/cargo-workspaces#46]
Is there a way to add newly created members to the root Cargo.toml file under `workspace.members`? 
Currently I add it manually whenever I create a new member project.
I would imagine that `cargo ws create` would automatically add the new project to the members list - but it doesn't.
Or even better if there was a separate command `cargo ws update` which finds all the dangling subprojects and either adds them to `workspace.members` or `workspace.exclude`.

**Comment by pksunkara** [comment]
https://github.com/pksunkara/cargo-workspaces/blob/772e6252fb3bb126796f9196fea5202337dfab9e/cargo-workspaces/src/create.rs#L76. Needs programmatic TOML editor first.

**Comment by pksunkara** [comment]
> the crate name should be inferred from the path - it's annoying to specify it twice.

**Comment by Diggsey** [comment]
Yeah I kindof thought this was the entire point of `cargo ws` was to be able to create new crates *in* the workspace...

**Comment by totikom** [comment]
There is [cargo sort](https://github.com/DevinR528/cargo-sort) command, that parses TOMLs and sorts dependencies and other fields.
Maybe use their code for parsing workspace manifest?

**Comment by pksunkara** [comment]
It uses `toml_edit` underneath which (even with the rewrite) doesn't keep the formatting.

**Comment by totikom** [comment]
Maybe we can do it in a `clippy --fix` way: warn user, that the formatting can be broken and deny to modify `Cargo.toml` unless it is backed up in `git`?

**Comment by Samathingamajig** [comment]
The entire reason I installed `cargo-workspaces` was because cargo doesn't automatically add a new crate to the workspace, and it doesn't even do it. This is a much-needed feature, it's annoying to manually go and add it.

Is there an example of where formatting the `Cargo.toml` changes the underlying data stored? Like if it's parsed, where the formatting would change any of the values. If not, I don't think formatting should be of any concern.

**Comment by cozyGalvinism** [comment]
Now that we have `cargo add`, that seems to keep the formatting? So I'd assume `cargo-workspaces` can use the same?

**Comment by Samathingamajig** [comment]
> if I'm right in thinking that most folks are using this for managing workspace monorepos.

the crate is called "cargo-workspaces" it'd be pretty cool if it could, idk, manage workspaces
