### ISSUE TITLE
Is there any way to disable global version tag?

### ISSUE THREAD

**Issue by vitalka200** [pksunkara/cargo-workspaces#47]
Is there any way to disable the global version tag?

When having multiple crates in the workspace that have a different release schedule I want to be able to disable the global version tag on minor/patch releases and turn it back on when making a major release. 

Is it currently possible?

**Comment by pksunkara** [comment]
You will have to explain your use case a bit more with examples. What is the global version tag you are talking about here?

**Comment by vitalka200** [comment]
I'm sorry for being too generic.

For example, in my use case, I have the following workspace structure
```
workspace
|-- package_1(cli)
|-- package_2 (lib)
|-- package_3 (cli)
```
Package #1 a cli util that does not depend on the Packages #2,3.  Package #3 depends on #2. 
Packages #2,3 updates much more frequently than #1.

Let's say I did a major release for all the packages and now all of them have the same version. For example `1.0.0`

The following tags were created:
```
package_1@v1.0.0
package_2@v1.0.0
package_3@v1.0.0
1.0.0
```

After that, there were small patches in packages #2 and #3 and now their version is `1.0.4` but #1 is still with the version `1.0.0` 

The problem is when only the `package_1`  have changes the `cargo workspaces version`  fails with an error
`error: unable to tag 1.0.1, out = , err = fatal: tag '1.0.1' already exists`

Ideally, I want the global version tag to be created only on major releases of the whole workspace and not for each package version bumps.

I hope I succeeded to explain it a little bit better.

**Comment by vitalka200** [comment]
The problematic line is this one
https://github.com/pksunkara/cargo-workspaces/blob/3464a4e5e7f86ac753fa82b81a9b9ef9b87ecdef/cargo-workspaces/src/utils/git.rs#L207

This leads to the creation of the global version tag `vX.Y.Z` in addition to the package's individual tag `package_name@vX.Y.Z` thus leading to git push conflict when packages updates are not synchronous.

@pksunkara,
Maybe it's worth adding a boolean flag `global_version_tag` or `workspace_version_tag` to control whether the tag `vX.Y.Z` is going to be created defaulting to false as `cargo-workspaces` intended to be used on workspaces with multiple packages?

**Comment by pksunkara** [comment]
I am thinking the solution is to add a new option `--no-global-tag` similar to `--no-individual-tags` we already have.

**Comment by vitalka200** [comment]
Yeah, the `--no-global-tag` should be enough... at least for the use-case I described

**Comment by pksunkara** [comment]
Would welcome a PR since I am a bit busy with other projects right now.

**Comment by vitalka200** [comment]
Hi @pksunkara, 
Is it possible to make a release with a #49 PR?
