### ISSUE TITLE
Publishing fails on windows because of line endings

### ISSUE THREAD

**Issue by ISibboI** [pksunkara/cargo-workspaces#52]
I am using git on windows with `core.autocrlf = true`. When staging and committing modified files from the PowerShell, everything works fine. However if I execute `cargo ws publish --allow-branch cargo-workspaces-bug custom 6.6.1-test.0` in the PowerShell, I get the following error:

```
PS D:\git\evalexpr> cargo ws publish --allow-branch cargo-workspaces-bug custom 6.6.1-test.0
info looking for changes since evalexpr@6.6.0
info current common version 6.6.0
Changes:
 - evalexpr: 6.6.0 => 6.6.1-test.0

✔ Are you sure you want to create these versions? · yes
Updating crates.io index
Updating evalexpr v6.6.0 (D:\git\evalexpr) -> v6.6.1-test.0
info version committing changes
error: unable to add files to git index, out = , err = warning: LF will be replaced by CRLF in Cargo.toml.
The file will have its original line endings in your working directory 
```

The files are staged afterwards, and executing git commit manually works fine as well.

I am using cargo workspaces version 0.2.24.

**Comment by pksunkara** [comment]
@ISibboI Is this still an issue?
