### ISSUE TITLE
list crates to be published

### ISSUE THREAD

**Issue by MarcoIeni** [pksunkara/cargo-workspaces#61]
Add a way to list crates to be published, for example `cargo ws publish --list`.
This will not publish the crates. Instead it will just list the crates that should be published.

I know there is `cargo ws changed`, but it checks git tags, not the cargo registry.

With this feature you can:
- use external tools to publish the repositories, for example [cloudsmith-cli](https://github.com/cloudsmith-io/cloudsmith-cli).
- have a quick look to what crates need to be published.
- pipe the result in other tools to get other functionalities (for example to generate changelog).

**Comment by pksunkara** [comment]
Added `cargo ws plan` subcommand for this.
