### ISSUE TITLE
workspace create does not show option for 2021 edition

### ISSUE THREAD

**Issue by vikigenius** [pksunkara/cargo-workspaces#63]
`cargo ws create` does not provide me with the option to chose 2021 edition. It shows only 2015 and 2018.

This despite `cargo new` using 2021 by default.

I am also using the latest release 0.2.28

**Comment by shymega** [comment]
Looks like this has been implemented in 1b004edc9ae8e26ff19b946d6b344942e6306ccd - a new release needs to be made. I too had this issue, but the sources would indicate it's been fixed.

I just built the tool from that commit, and I can confirm the 2021 edition is now accessible.

**Comment by pksunkara** [comment]
Released in 0.2.29
