### ISSUE TITLE
`publish`: create and push git tags

### ISSUE THREAD

**Issue by MarcoIeni** [pksunkara/cargo-workspaces#69]
Can the command `cargo workspaces publish` create and push a tag after/before the crate is published?

**Comment by pksunkara** [comment]
It does before publishing.

**Comment by MarcoIeni** [comment]
Oh, I see. It does it normally, but not when the `--from-git` flag is set.
Would it be possible to add tags even when this flag is set?

**Comment by pksunkara** [comment]
That flag is used when you are supposed to already have tags. Maybe you want a different things? What are you trying to do?

**Comment by MarcoIeni** [comment]
My use case is that Cargo.toml contains the new version and is committed in git.
That's why I use the `--from-git` flag. However, I wish I could create the tag automatically with cargo workspaces when publishing.
Cargo.toml is updated with https://github.com/MarcoIeni/release-plz

**Comment by pksunkara** [comment]
From the wisdom of all the last few years of working with release tools in all kinds of package managers, the tool which updates `Cargo.toml` and commits needs to be the same tool which creates the tags too. In this case, `release-plz` is the one that needs to create tags, if you don't plan to use `cargo workspaces` version bumping functionality.
