### ISSUE TITLE
Publish reads from wrong registry when --registry option provided

### ISSUE THREAD

**Issue by leighmcculloch** [pksunkara/cargo-workspaces#79]
The `cargo workspaces publish` command accepts a `--registry` option that allows for specifying the registry that the publish will occur to. The value is passed down to the `cargo publish` command successfully.

However, `cargo workspaces publish` also constructs an `Index` that is used for checking if the crate is published that when creating that index it ignores the passed in `--registry` parameter.

This has two impacts:

- The publish command will check either the default (crates.io) registry or a registry specified in the Cargo.toml file when checking if the version already exists before publishing, rather than checking the specified registry. So it will attempt to republish and error in cases it shouldn't.

- The publish command will check either the default (crates.io) registry or a registry specified in the Cargo.toml file when checking if the version has successfully been published, rather than checking the specified registry. So it will wait forever thinking the crate has never published.

**Comment by pksunkara** [comment]
This will be fixed with the new sparse registry.

**Comment by pksunkara** [comment]
This has been fixed in recent 0.3. Can you please check and confirm?
