### ISSUE TITLE
Fails in latest arch linux with libssl.so.1.1 not found

### ISSUE THREAD

**Issue by sigmaSd** [pksunkara/cargo-workspaces#81]
ldd cargo-workspaces
```
        linux-vdso.so.1 (0x00007fffe95e6000)
        libssl.so.1.1 => not found
        libcrypto.so.1.1 => not found
        libz.so.1 => /usr/lib/libz.so.1 (0x00007f9f0af00000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f9f0aee0000)
        libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f9f0aedb000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f9f0a918000)
        libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f9f0aed4000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f9f0a731000)
        /lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007f9f0af5c000)
```
ldd cargo
```
...
libssl.so.3 => /usr/lib/libssl.so.3 (0x00007f8957160000)
libcrypto.so.3 => /usr/lib/libcrypto.so.3 (0x00007f8956c00000)
...
```

**Comment by pksunkara** [comment]
It's an issue of your packages. Can't do anything on my side. I use arch linux too.

**Comment by sigmaSd** [comment]
https://old.reddit.com/r/archlinux/comments/ymf5e5/psa_openssl_upgrades_from_111_to_307_breaking/

**Comment by sebschmi** [comment]
The problem here is that OpenSSL 1.1 will only be supported until 11th September 2023, and [their website](https://www.openssl.org/source/) recommends all users to upgrade as soon as possible:

> The latest stable version is the 3.0 series supported until 7th September 2026. This is also a Long Term Support (LTS) version. The previous LTS version (the 1.1.1 series) is also available and is supported until 11th September 2023. All older versions (including 1.1.0, 1.0.2, 1.0.0 and 0.9.8) are now out of support and should not be used. Users of these older versions are encouraged to upgrade to 3.0 as soon as possible.

Various distributions (including also the widely-used ubuntu) have upgraded to 3.0 already, hence I recommend reopening this, or creating a new issue for upgrading OpenSSL to 3.0 ASAP.
