### ISSUE TITLE
`cargo workspaces publish` fails in the middle with spurious network error

### ISSUE THREAD

**Issue by klebs6** [pksunkara/cargo-workspaces#83]
hi folks!

I am getting an error here when I attempt to publish the crates in a workspace.

Unfortunately, I havn't been able to determine the fix for this, other than to retry the whole process again -- crossing my fingers that it doesn't happen again!  

This is tedious and it makes me wonder whether there is a better way.  Currently, I keep bumping the patch version to fix the problem when it occurs.  This seems like no solution at all!

Please, what happens if `cargo workspaces publish` fails?? How can I recover without restarting the whole procedure?

**Comment by klebz** [comment]
It looks like this:
```
warning: spurious network error (2 tries remaining): http parser error: stream ended at an unexpected time; class=Http (34)

```

**Comment by pksunkara** [comment]
You can just re-run with `--from-git` option. It will not change versions and automatically not publish any previously published packages.

**Comment by klebs6** [comment]
thanks!! at some point I figured this out on my own too, but this solution works for me!
