### ISSUE TITLE
glob pattern matching does not allow alternate "or"

### ISSUE THREAD

**Issue by mike-code** [pksunkara/cargo-workspaces#85]
I noticed that the [glob pattern matching ](https://github.com/pksunkara/cargo-workspaces/blob/81c0ac742139e0e86edc8f93b14a45832515b450/cargo-workspaces/src/utils/git.rs#L7) used here does not allow alternate "or" pattern such as `(foo|bar)baz` or `{foo,bar}baz` that would match both `foobaz` and `barbaz`. There's an [open issue](https://github.com/rust-lang/glob/issues/2) from 2014 that hasn't been addressed thus I don't think that it'll ever be implemented in the `glob` crate. I'd suggest to use an alternative crate for the glob pattern matching such as [globset](https://crates.io/crates/globset) that does support [this feature](https://github.com/BurntSushi/ripgrep/blob/master/crates/globset/README.md?plain=1#L113), among other improvements.

For the record, my usecase was to have `--allow-branch '(hotfix|release)/**'` but that won't go through the glob pattern matching whilst `allow-branch` can only be used once (accepts a single string instead of array of strings).

**Comment by fosskers** [comment]
I just hit this issue as well, except when trying to use the `--ignore-changes` option to try and filter out crates I didn't want to update.
