### ISSUE TITLE
Option to ignore workspace members

### ISSUE THREAD

**Issue by bluejekyll** [pksunkara/cargo-workspaces#97]
I've been integrating cargo-workspaces with a new justfile based approach away from a former tool that I've been using. One thing my projects have a lot of features that need to be tested, on and off, some workspace members support those feature flags while others don't.

I solved this previously with an ignore option on workspace commands. I was wondering if you'd consider a new flag like `--ignore-members={list of workspace members to ignore}` as an option on exec and others?

**Comment by pksunkara** [comment]
Feel free to send a PR. I have a similar option in `rename` subcommand.
